// One headless worker. Actual public batch first; fault cases are explicitly replayed.
import { chromium } from 'playwright';
import { writeFile, readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { PUBLIC_BATCH_CSV, parseCSV } from '../web/batch.mjs';
const root=new URL('../',import.meta.url),checks=[],errors=[],requests=[],resources=new Set();let passed=false;
process.env.PORT='4330';const {server}=await import('./server.mjs');
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,reducedMotion:'reduce'}),page=await context.newPage();
page.on('pageerror',e=>errors.push(e.message));let source='actual_public_rpc';
page.on('request',r=>{resources.add(new URL(r.url()).origin);if(new URL(r.url()).origin==='https://rpc.mainnet.arc.io'){const q=r.postDataJSON();requests.push({source,at:Date.now(),method:q.method,params:q.params});}});
const done=()=>page.waitForFunction(()=>document.getElementById('batch-cancel').hidden,{}, {timeout:65000});
const download=async(id,name)=>{const pending=page.waitForEvent('download');await page.locator('#'+id).click();const d=await pending;await d.saveAs(new URL(name,root).pathname);return readFile(new URL(name,root),'utf8');};
const states=()=>page.locator('.batch-state').allTextContents();
const importCSV=async(text)=>page.locator('#batch-file').setInputFiles({name:'review.csv',mimeType:'text/csv',buffer:Buffer.from(text)});
try{
 await page.goto('http://127.0.0.1:4330');await page.locator('#batch-panel summary').first().focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#batch-panel').getAttribute('open'),'');await page.locator('#batch-example').click();assert.equal(requests.length,0);assert.equal(await page.locator('.batch-row').count(),5);checks.push({case:'Keyboard entry, five-record preview and duplicate detection before any RPC request',source:'local_input'});
 await page.locator('#batch-run').click();await done();assert.deepEqual(await states(),['Expected net matched','Above expected net','Below expected net','Repeated input','Could not verify']);const actual=requests.filter(r=>r.source==='actual_public_rpc');assert.equal(actual.length,9);assert.equal(actual.filter(r=>r.method==='eth_getTransactionReceipt').length,3);assert.ok(actual.slice(1).every((r,i)=>r.at-actual[i].at>=350));assert.deepEqual(await page.locator('.batch-row').nth(1).locator('dd').allTextContents(),['1458.033036 USDC','0 USDC','1458.033036 USDC','0.033036 USDC']);assert.deepEqual(await page.locator('.batch-row').nth(2).locator('dd').allTextContents(),['1458.033036 USDC','1458.033036 USDC','0 USDC','-1 USDC']);assert.match(await page.locator('.batch-row').nth(2).textContent(),/not merchant nonpayment evidence/);assert.match(await page.locator('.batch-row').nth(3).textContent(),/not another on-chain payment/);await page.screenshot({path:new URL('evidence/desktop-batch.png',root).pathname,fullPage:true});checks.push({case:'Genuine batch: exact/above/below, repeated input and missing receipt; shared evidence and paced requests',source:'actual_public_rpc',reads:9,minObservedRequestGapMs:Math.min(...actual.slice(1).map((r,i)=>r.at-actual[i].at))});
 const exceptions=await download('batch-export','evidence/batch-exceptions.csv');const records=parseCSV(exceptions);assert.equal(records.length,5);assert.ok(records.slice(1).every(r=>r[1]!=='Expected net matched'));assert.match(exceptions,/not merchant nonpayment evidence/);checks.push({case:'Actual exception export retains four exception records and zero-net context',source:'actual_public_rpc_export'});
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'batch overflow at '+width);}await page.setViewportSize({width:390,height:844});await page.locator('#batch-panel').scrollIntoViewIfNeeded();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));for(const id of ['batch-import','batch-template','batch-example','batch-run','batch-export'])assert.ok((await page.locator('#'+id).boundingBox()).height>=44);await page.screenshot({path:new URL('evidence/mobile-batch.png',root).pathname,fullPage:true});await page.setViewportSize({width:1440,height:1000});checks.push({case:'Batch results fit320/390/768/1440px and five main batch actions meet44px height',source:'local_layout_with_actual_results'});
 await page.locator('.batch-row').first().getByRole('button',{name:'Open receipt & evidence'}).click();assert.equal(await page.locator('#net').textContent(),'100.01');assert.equal(await page.locator('#batch-panel').getAttribute('open'),null);const evidence=JSON.parse(await download('download','evidence/batch-row-receipt.json'));assert.equal(evidence.mode,'live_rpc');assert.equal(evidence.reviewScope.comparisonBasis,'transaction_net');const chooser=page.waitForEvent('filechooser');await page.locator('#import-result').click();await (await chooser).setFiles(new URL('evidence/batch-row-receipt.json',root).pathname);await page.locator('#recheck-note').waitFor({state:'visible',timeout:65000});assert.match(await page.locator('#recheck-note').textContent(),/Recheck consistent/);checks.push({case:'Actual batch row reuses the single receipt export and saved-file recompute/fresh-recheck path',source:'actual_public_rpc',extraReads:4});
 source='labelled_replay';await page.locator('#batch-panel summary').first().click();const saved=JSON.parse(await readFile(new URL('evidence/browser-live-receipt.json',root),'utf8'));let rateLimit=false,holdReceipt=false,startedReceipt;
 await page.route('https://rpc.mainnet.arc.io',async route=>{const q=route.request().postDataJSON();if(rateLimit){await route.fulfill({status:429,body:'Busy'});return;}if(holdReceipt&&q.method==='eth_getTransactionReceipt'){startedReceipt?.();return;}const e=saved.evidence;const result=({eth_chainId:e.chainId,eth_getTransactionReceipt:q.params[0]===saved.transactionHash?e.receipt:null,eth_getBlockByNumber:e.block,eth_blockNumber:e.head})[q.method];await route.fulfill({contentType:'application/json',body:JSON.stringify({jsonrpc:'2.0',id:q.id,result})});});
 const basic=PUBLIC_BATCH_CSV.split('\r\n')[0]+'\r\n'+PUBLIC_BATCH_CSV.split('\r\n')[1]+'\r\n';
 await importCSV(basic);await page.waitForFunction(()=>document.querySelectorAll('.batch-row').length===1);await importCSV('bad,header\n1,2');await page.locator('#batch-error').waitFor({state:'visible'});assert.equal(await page.locator('.batch-row').count(),1);assert.match(await page.locator('#batch-summary').textContent(),/Previous batch retained/);checks.push({case:'Bad replacement CSV reports the header problem and retains the prior batch',source:'local_invalid_file'});
 const unsafe='tx_hash,address,expected_net_usdc\r\n"=1+1",'+saved.recipient+',1\r\n'+basic.split('\r\n')[1]+'\r\n';await importCSV(unsafe);await page.waitForFunction(()=>document.querySelectorAll('.batch-row').length===2);await page.locator('#batch-run').click();await done();assert.deepEqual(await states(),['Invalid input','Expected net matched']);const safe=parseCSV(await download('batch-export','evidence/batch-safe-exceptions.csv'));assert.equal(safe[1][2],"'=1+1");checks.push({case:'One invalid formula-like row survives alongside a good row; exception export prefixes it as literal text',source:'labelled_replay_and_local_csv'});
 await importCSV(basic+basic.split('\r\n')[1].replace(saved.transactionHash,'0x'+'0'.repeat(64))+'\r\n');await page.waitForFunction(()=>document.querySelectorAll('.batch-row').length===2);rateLimit=true;const before=requests.length;await page.locator('#batch-run').click();await done();assert.deepEqual(await states(),['Could not verify','Not checked']);assert.equal(requests.length-before,1);rateLimit=false;checks.push({case:'Replayed429 stops extra requests and preserves the unqueried record',source:'injected_http429'});
 await importCSV(basic+basic.split('\r\n')[1].replace(saved.transactionHash,'0x'+'0'.repeat(64))+'\r\n');holdReceipt=true;const receiptStarted=new Promise(resolve=>startedReceipt=resolve);await page.locator('#batch-run').click();await receiptStarted;assert.equal(await page.locator('#verify').isDisabled(),true);await page.locator('#batch-cancel').click();await done();assert.deepEqual(await states(),['Cancelled','Not checked']);assert.equal(await page.locator('#verify').isDisabled(),false);checks.push({case:'Cancellation aborts in-flight observation, retains both records and restores single-review controls',source:'injected_delayed_rpc'});
 assert.ok([...resources].every(origin=>['http://127.0.0.1:4330','https://rpc.mainnet.arc.io'].includes(origin)));assert.ok(requests.every(({method,params})=>method==='eth_getTransactionReceipt'?params.length===1&&/^0x[0-9a-f]{64}$/.test(params[0]):method==='eth_getBlockByNumber'?params.length===2&&/^0x[0-9a-f]+$/.test(params[0])&&params[1]===false:['eth_chainId','eth_blockNumber'].includes(method)&&params.length===0));assert.deepEqual(errors,[]);passed=true;
}finally{await writeFile(new URL('evidence/batch-validation.json',root),JSON.stringify({checkedAt:new Date().toISOString(),passed,checks,errors,requests,resources:[...resources],actualPublicRPCReads:requests.filter(r=>r.source==='actual_public_rpc').length,maxRows:20,maxCSVBytes:100000,concurrency:1,requestDelayMs:350,writes:0,published:false,scope:'Comparisons with user-supplied transaction-net expectations, not invoice settlement. Repeated input is not another on-chain payment.',sampleLimit:'Two existing public transactions; all-zero hash deliberately absent; not user earnings or known merchant receipts.'},null,2)+'\n');await browser.close();server.close();}
console.log(JSON.stringify({passed,checks:checks.length,actualPublicRPCReads:requests.filter(r=>r.source==='actual_public_rpc').length,errors}));
