import {chromium} from 'playwright';
import {readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {ARC} from '../web/verifier.mjs';
const root=new URL('../',import.meta.url);process.env.PORT='4314';const {server}=await import('./server.mjs');
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const checks=[],errors=[],rpcMethods=new Set();let liveWrites=0,complete=false;
const watch=page=>{page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(new URL(r.url()).origin===ARC.rpc&&r.method()==='POST'){const method=r.postDataJSON()?.method;rpcMethods.add(method);if(!['eth_chainId','eth_getTransactionReceipt','eth_getBlockByNumber','eth_blockNumber'].includes(method))liveWrites++;}});};
const context=await browser.newContext({viewport:{width:1440,height:1200},acceptDownloads:true});const page=await context.newPage();watch(page);
const base='http://127.0.0.1:4314';
const done=async(p=page)=>p.waitForFunction(()=>!document.getElementById('verify').disabled&&document.getElementById('loading').hidden,{}, {timeout:65000});
const exportFile=async(id,p=page)=>{const pending=p.waitForEvent('download');await p.locator(id).click();return readFile(await(await pending).path(),'utf8');};
const assertResult=async(status,p=page)=>{await done(p);assert.equal(await p.locator('#error').isVisible(),false,await p.locator('#error').textContent());assert.equal(await p.locator('#status').textContent(),status);};
const inject=async(evidence,override={})=>{await page.unroute(ARC.rpc);await page.route(ARC.rpc,async route=>{const q=route.request().postDataJSON();const result=Object.hasOwn(override,q.method)?override[q.method]:({eth_chainId:evidence.chainId,eth_getTransactionReceipt:evidence.receipt,eth_getBlockByNumber:evidence.block,eth_blockNumber:evidence.head})[q.method];await route.fulfill({contentType:'application/json',body:JSON.stringify({jsonrpc:'2.0',id:q.id,result})});});};
try{
 await page.goto(base);await page.getByRole('heading',{name:'Verify USDC. Know what arrived.'}).waitFor();
 assert.equal((await context.request.get(base+'/.git/config')).status(),404);assert.equal(await page.locator('#result').isVisible(),false);checks.push({case:'Initial desktop and server allowlist',source:'local'});
 await page.screenshot({path:new URL('evidence/desktop-empty.png',root).pathname,fullPage:true});
 await page.locator('#verify').click();await done();assert.equal(await page.locator('#tx').getAttribute('aria-invalid'),'true');assert.equal(await page.locator('#tx').evaluate(el=>el===document.activeElement),true);checks.push({case:'Inline invalid input with keyboard focus',source:'local'});
 await page.locator('#sample').click();assert.equal(await page.locator('#net').textContent(),'12.5');assert.match(await page.locator('#mode').textContent(),/SYNTHETIC/);assert.equal(await page.locator('#explorer').isVisible(),false);
 const synthetic=JSON.parse(await exportFile('#download'));assert.equal(synthetic.mode,'synthetic_offline_example');assert.equal(synthetic.rpcURL,null);assert.match(await exportFile('#download-readable'),/SYNTHETIC EXAMPLE/);checks.push({case:'Synthetic mode unmistakable in UI and both exports',source:'local'});
 await page.screenshot({path:new URL('evidence/desktop-offline.png',root).pathname,fullPage:true});
 await page.locator('#amount').fill('12.51');assert.equal(await page.locator('#result').isVisible(),false);checks.push({case:'Editing clears previous observation',source:'local'});
 await page.locator('#live-example').click();await assertResult('Exact amount matched');assert.equal(await page.locator('#net').textContent(),'268.350916');assert.equal(await page.locator('#check-count').textContent(),'6 / 6 checks passed');assert.match(await page.locator('#block-time').textContent(),/UTC/);
 const live=JSON.parse(await exportFile('#download'));assert.equal(live.mode,'live_rpc');assert.equal(live.minConfirmations,1);assert.equal(live.evidence.receipt.status,'0x1');assert.equal(live.ignoredDuplicateStreamLogs,1);await writeFile(new URL('evidence/browser-live-receipt.json',root),JSON.stringify(live,null,2)+'\n');checks.push({case:'Real mainnet exact receipt, six explicit checks, Arc one-block default',source:'actual_public_rpc',tx:live.transactionHash});
 const html=await exportFile('#download-readable');assert.ok(!html.includes('<script'));assert.ok(html.includes(live.transactionHash));assert.match(html,/Unsigned RPC observation/);await writeFile(new URL('evidence/readable-public-receipt.html',root),html);checks.push({case:'Readable HTML receipt with full identifiers and trust boundary',source:'actual_public_rpc'});
 await page.screenshot({path:new URL('evidence/desktop-mainnet.png',root).pathname,fullPage:true});
 await page.locator('#movement-detail summary').click();assert.equal(await page.locator('.movement').count(),1);assert.match(await page.locator('#stream-note').textContent(),/1 ERC-20/);checks.push({case:'Movement drill-down counts canonical stream once',source:'actual_public_rpc'});await page.locator('#movement-detail summary').click();
 await page.locator('#receipt-file').setInputFiles({name:'receipt.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(live))});await page.locator('#recheck-note').waitFor({state:'visible',timeout:65000});await assertResult('Exact amount matched');assert.match(await page.locator('#recheck-note').textContent(),/Recheck consistent/);checks.push({case:'Saved evidence reimported and fetched fresh from mainnet',source:'actual_public_rpc'});
 const tampered={...live,status:'no_payment',netReceivedUSDC:'999',rpcURL:'https://attacker.invalid'};await page.locator('#receipt-file').setInputFiles({name:'edited.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(tampered))});await page.waitForFunction(()=>document.getElementById('recheck-note').textContent.includes('Saved claims differ'),{}, {timeout:65000});await assertResult('Exact amount matched');assert.match(await page.locator('#recheck-note').textContent(),/Saved claims differ/);assert.equal(await page.locator('#net').textContent(),'268.350916');checks.push({case:'Tampered saved amount/status flagged; supplied endpoint ignored',source:'modified_saved_claims_then_actual_public_rpc'});
 await page.locator('#roundtrip-example').click();await assertResult('No positive net receipt');assert.equal(await page.locator('#net').textContent(),'0');assert.match(await page.locator('#amount-comparison').textContent(),/Short by 1458.033036/);const zero=JSON.parse(await exportFile('#download'));assert.equal(zero.incomingUSDC,zero.outgoingUSDC);assert.equal(zero.status,'no_net_receipt');await writeFile(new URL('evidence/mainnet-roundtrip.json',root),JSON.stringify(zero,null,2)+'\n');await page.screenshot({path:new URL('evidence/desktop-zero-net.png',root).pathname,fullPage:true});checks.push({case:'Real successful transaction forwards all funds; never shown paid',source:'actual_public_rpc',tx:zero.transactionHash});
 const mobileContext=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1});const mobile=await mobileContext.newPage();watch(mobile);await mobile.goto(base);await mobile.locator('#live-example').click();await assertResult('Exact amount matched',mobile);assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.locator('#result').scrollIntoViewIfNeeded();await mobile.screenshot({path:new URL('evidence/mobile-receipt.png',root).pathname});await mobile.evaluate(()=>scrollTo(0,0));await mobile.screenshot({path:new URL('evidence/mobile-mainnet.png',root).pathname});checks.push({case:'390px mobile real mainnet receipt and viewport screenshots',source:'actual_public_rpc'});
 await mobile.setViewportSize({width:320,height:844});assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await mobile.locator('#verify').evaluate(el=>el.getBoundingClientRect().height>=44));await mobileContext.close();checks.push({case:'320px mobile no horizontal overflow and touch-size primary action',source:'local_layout'});
 // All cases below inject abnormal responses. They are NOT claimed as live chain transactions.
 await inject(live.evidence);await page.locator('#live-example').click();await assertResult('Exact amount matched');await page.locator('#tx').fill(ARC.explorer+'/tx/'+live.transactionHash);await page.locator('#amount').fill('268.350917');await page.locator('#verify').click();await assertResult('Amount needs review');assert.match(await page.locator('#amount-comparison').textContent(),/Short by 0.000001/);assert.equal(await page.locator('#tx').inputValue(),live.transactionHash);checks.push({case:'Explorer URL normalization and exact underpayment difference',source:'replayed_public_evidence_fixture'});
 await page.locator('#amount').fill('268.350915');await page.locator('#verify').click();await assertResult('Amount needs review');assert.match(await page.locator('#amount-comparison').textContent(),/Above expected by 0.000001/);checks.push({case:'Overpayment remains review state',source:'replayed_public_evidence_fixture'});
 for(const [name,override,code] of [['Another chain',{eth_chainId:'0x1'},'wrong_chain'],['Absent receipt',{eth_getTransactionReceipt:null},'not_mined'],['Reverted transaction',{eth_getTransactionReceipt:{...live.evidence.receipt,status:'0x0'}},'failed_transaction'],['Block mismatch',{eth_getBlockByNumber:{...live.evidence.block,hash:'0x'+'a'.repeat(64)}},'reorg_or_inconsistent']]){await inject(live.evidence,override);await page.locator('#live-example').click();await done();assert.equal(await page.locator('#error-code').textContent(),code);assert.equal(await page.locator('#result').isVisible(),false);checks.push({case:name+' clears receipt with specific recovery text',source:'injected_abnormal_rpc_fixture'});}
 const inconsistent=structuredClone(live.evidence);inconsistent.receipt.logs.find(l=>l.address.toLowerCase()===ARC.usdc).data='0x'+1n.toString(16).padStart(64,'0');await inject(inconsistent);await page.locator('#live-example').click();await done();assert.equal(await page.locator('#error-code').textContent(),'inconsistent_streams');checks.push({case:'Conflicting ERC20/native stream refused in UI',source:'injected_abnormal_rpc_fixture'});
 await page.unroute(ARC.rpc);await page.route(ARC.rpc,r=>r.fulfill({status:429,contentType:'application/json',body:'{}'}));await page.locator('#live-example').click();await done();assert.equal(await page.locator('#error-code').textContent(),'rate_limited');assert.equal(await page.locator('#result').isVisible(),false);await page.screenshot({path:new URL('evidence/desktop-rpc-busy.png',root).pathname,fullPage:true});checks.push({case:'Rate-limit error has recovery action and no payment conclusion',source:'injected_http_429'});
 await page.unroute(ARC.rpc);await page.route(ARC.rpc,async r=>{await new Promise(resolve=>setTimeout(resolve,350));await r.abort().catch(()=>{});});await page.locator('#live-example').click();await page.locator('#cancel').click();await page.waitForTimeout(500);assert.equal(await page.locator('#empty').isVisible(),true);assert.equal(await page.locator('#result').isVisible(),false);checks.push({case:'Cancellation prevents delayed response from rendering stale receipt',source:'injected_delayed_transport'});
 await page.evaluate(()=>{const original=File.prototype.text;File.prototype.text=async function(){await new Promise(resolve=>setTimeout(resolve,350));return original.call(this);};});await page.locator('#receipt-file').setInputFiles({name:'slow.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(live))});await page.locator('#amount').fill('99');await page.waitForTimeout(600);assert.equal(await page.locator('#amount').inputValue(),'99');assert.equal(await page.locator('#empty').isVisible(),true);checks.push({case:'Editing during receipt-file read prevents stale import takeover',source:'injected_delayed_local_file_read'});
 assert.equal(liveWrites,0);assert.deepEqual(errors,[]);assert.deepEqual([...rpcMethods].sort(),['eth_blockNumber','eth_chainId','eth_getBlockByNumber','eth_getTransactionReceipt'].sort());checks.push({case:'Only four read RPC methods, no wallet/write calls or runtime errors',source:'all_observed_requests'});complete=true;
}finally{await writeFile(new URL('evidence/browser-qa.json',root),JSON.stringify({checkedAt:new Date().toISOString(),checks,errors,liveWrites,rpcMethods:[...rpcMethods],passed:complete&&errors.length===0&&liveWrites===0},null,2)+'\n');await browser.close();server.close();}
console.log(JSON.stringify({checks,errors,liveWrites},null,2));
