// One isolated headless worker. Real public demos first, labelled faults afterwards.
import { chromium } from 'playwright';
import { readFile, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { parseCSV } from '../web/batch.mjs';
import { recomputeOrderBundle, SPLIT_ORDER_DEMO } from '../web/orders.mjs';
const root=new URL('../',import.meta.url),checks=[],errors=[],requests=[],resources=new Set();let source='actual_public_rpc',passed=false;
process.env.PORT='4331';const {server}=await import('./server.mjs');
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,reducedMotion:'reduce'}),page=await context.newPage();
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{const origin=new URL(r.url()).origin;resources.add(origin);if(origin==='https://rpc.mainnet.arc.io'){const q=r.postDataJSON();requests.push({source,at:Date.now(),method:q.method,params:q.params});}});
const done=()=>page.waitForFunction(()=>document.getElementById('order-cancel').hidden,{}, {timeout:65000});
const statuses=()=>page.locator('.order-card .batch-state').allTextContents();
const download=async(id,name)=>{const pending=page.waitForEvent('download');await page.locator('#'+id).click();const d=await pending;await d.saveAs(new URL(name,root).pathname);return readFile(new URL(name,root),'utf8');};
const importCSV=async(text)=>page.locator('#order-file').setInputFiles({name:'orders.csv',mimeType:'text/csv',buffer:Buffer.from(text)});
try{
 await page.goto('http://127.0.0.1:4331');await page.locator('#order-panel>summary').focus();await page.keyboard.press('Enter');await page.locator('#order-split-demo').click();assert.equal(requests.length,0);assert.equal(await page.locator('#order-demo-note').isVisible(),true);assert.match(await page.locator('#order-demo-note').textContent(),/not customer bills/);assert.equal(await page.locator('.order-card').count(),2);checks.push({case:'Keyboard entry, local preview and unmistakable illustrative order labels before RPC',source:'local_demo_input'});
 await page.locator('#batch-panel>summary').click();await page.locator('#batch-example').click();await page.locator('#order-run').click();assert.equal(await page.locator('#batch-run').isDisabled(),true);assert.equal(await page.locator('#batch-cancel').isVisible(),false);await done();assert.deepEqual(await statuses(),['Aggregate net matched','Incomplete observations']);assert.deepEqual(await page.locator('.order-card').first().locator('dd').allTextContents(),['1558.043036','1558.043036','0','2']);assert.match(await page.locator('.order-card').first().textContent(),/counted once/);assert.equal(requests.length,8);assert.equal(requests.filter(r=>r.method==='eth_getTransactionReceipt').length,3);assert.ok(requests.slice(1).every((r,i)=>r.at-requests[i].at>=350));await page.locator('#batch-panel>summary').click();await page.locator('.order-card').first().locator('summary').click();await page.screenshot({path:new URL('evidence/desktop-orders-full.png',root).pathname,fullPage:true});await page.locator('#order-panel').screenshot({path:new URL('evidence/desktop-orders.png',root).pathname});checks.push({case:'Actual two-transfer aggregate matches1558.043036, repeat counted once, missing order stays incomplete; other query modes disabled',source:'actual_public_rpc',reads:8});
 const csv=parseCSV(await download('order-export','evidence/order-comparisons.csv'));assert.equal(csv.length,3);assert.equal(csv[1][2],'1558.043036');assert.equal(csv[1][3],'1558.043036');assert.match(csv[1].at(-1),/DEMO: illustrative/);const bundleText=await download('order-bundle','evidence/order-demo-bundle.json');const independent=recomputeOrderBundle(bundleText);assert.equal(independent.orders[0].observedNetUSDC,'1558.043036');assert.equal(independent.orders[0].observedPayments,2);assert.equal(independent.orders[1].status,'incomplete');assert.equal(independent.claimedOrdersTrusted,false);checks.push({case:'Exported order comparisons carry demo/trust labels; saved raw evidence independently recomputes aggregate without trusting summary',source:'actual_export_offline_recompute'});
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'order overflow at '+width);}await page.setViewportSize({width:390,height:844});for(const id of ['order-import','order-template','order-split-demo','order-conflict-demo','order-run','order-export','order-exceptions','order-bundle'])assert.ok((await page.locator('#'+id).boundingBox()).height>=44);await page.screenshot({path:new URL('evidence/mobile-orders-full.png',root).pathname,fullPage:true});await page.locator('#order-demo-note').evaluate(el=>el.scrollIntoView({block:'start'}));await page.screenshot({path:new URL('evidence/mobile-orders.png',root).pathname});await page.setViewportSize({width:1440,height:1000});checks.push({case:'Expanded order/payment evidence fits320/390/768/1440px; eight order actions meet44px',source:'local_layout_with_actual_results'});
 await page.locator('.order-payment').first().getByRole('button',{name:'Open receipt & evidence'}).click();assert.equal(await page.locator('#status').textContent(),'Positive transaction net observed');assert.equal(await page.locator('#amount').inputValue(),'');const receipt=JSON.parse(await download('download','evidence/order-row-receipt.json'));assert.equal(receipt.expectedAmountUSDC,null);assert.equal(receipt.reviewScope.comparisonBasis,'transaction_net');const chooser=page.waitForEvent('filechooser');await page.locator('#import-result').click();await(await chooser).setFiles(new URL('evidence/order-row-receipt.json',root).pathname);await page.locator('#recheck-note').waitFor({state:'visible',timeout:65000});assert.match(await page.locator('#recheck-note').textContent(),/Recheck consistent/);checks.push({case:'Actual per-payment receipt preserves no per-row expectation; individual JSON recompute/fresh-recheck works',source:'actual_public_rpc',reads:4});
 await page.locator('#order-panel>summary').click();await page.locator('#order-conflict-demo').click();const before=requests.length;await page.locator('#order-run').click();await done();assert.deepEqual(await statuses(),['Allocation conflict','Allocation conflict','Aggregate net matched']);assert.equal(requests.length-before,4);assert.match(await page.locator('.order-card').first().textContent(),/comparison is withheld/);await page.screenshot({path:new URL('evidence/order-allocation-conflicts.png',root).pathname,fullPage:true});checks.push({case:'Actual conflict demo never queries/counts the shared hash; unrelated order still verifies',source:'actual_public_rpc',reads:4});
 source='labelled_replay';const saved=JSON.parse(await readFile(new URL('evidence/browser-live-receipt.json',root),'utf8')),SWAP='0x1732bf16a26831ba5a7d183ceb35c893bb9053630f9549ed99269985ab62d7d8';let delayed=false,started;
 await page.route('https://rpc.mainnet.arc.io',async route=>{const q=route.request().postDataJSON();if(delayed&&q.method==='eth_getTransactionReceipt'&&q.params[0]===SWAP){started?.();return;}const e=saved.evidence,result=({eth_chainId:e.chainId,eth_getTransactionReceipt:q.params[0]===saved.transactionHash?e.receipt:null,eth_getBlockByNumber:e.block,eth_blockNumber:e.head})[q.method];await route.fulfill({contentType:'application/json',body:JSON.stringify({jsonrpc:'2.0',id:q.id,result})});});
 await importCSV('wrong,header\n1,2');await page.locator('#order-error').waitFor({state:'visible'});assert.equal(await page.locator('.order-card').count(),3);assert.match(await page.locator('#order-summary').textContent(),/Previous order file retained/);checks.push({case:'Bad replacement CSV reports fields and retains the prior order file',source:'local_bad_file'});
 const consistentSplit=SPLIT_ORDER_DEMO.split('\r\n').slice(0,3).join('\r\n')+'\r\n';await importCSV(consistentSplit);await page.waitForFunction(()=>document.querySelectorAll('.order-card').length===1);delayed=true;const secondStarted=new Promise(resolve=>started=resolve);await page.locator('#order-run').click();await secondStarted;assert.match(await page.locator('.order-card').textContent(),/100.01/);assert.equal(await page.locator('#batch-run').isDisabled(),true);await page.locator('#order-cancel').click();await done();assert.deepEqual(await statuses(),['Incomplete observations']);assert.deepEqual(await page.locator('.order-card dd').allTextContents(),['1558.043036','100.01','Comparison withheld','1']);assert.equal(await page.locator('#verify').isDisabled(),false);assert.equal(await page.locator('#batch-run').isDisabled(),false);checks.push({case:'Cancellation retains first observed100.01, leaves order incomplete and restores batch/single controls',source:'injected_delayed_second_receipt'});
 const beforeInvalid=requests.length;await importCSV(await readFile(new URL('evidence/independent-invalid-address-conflict.csv',root),'utf8'));await page.waitForFunction(()=>document.querySelectorAll('.order-card').length===2);assert.deepEqual(await statuses(),['Allocation conflict','Allocation conflict']);assert.equal(await page.locator('#order-run').isDisabled(),true);assert.equal(requests.length,beforeInvalid);checks.push({case:'Exact independent invalid-address fixture blocks both hash allocations during preview with no RPC',source:'exact_independent_fixture_local_input'});
 const extraOnly=await readFile(new URL('evidence/independent-extra-only-records.csv',root),'utf8'),shortExtra=extraOnly.split('\n').slice(0,3).join('\n');await importCSV(shortExtra);await page.waitForFunction(()=>document.querySelectorAll('.order-card').length===1);assert.match(await page.locator('#order-summary').textContent(),/2 input records/);assert.match(await page.locator('#order-unassigned').textContent(),/Unassigned record 3/);assert.match(await page.locator('#order-unassigned').textContent(),/unexpected-extra/);await page.locator('#order-run').click();await done();const malformed=JSON.parse(await download('order-bundle','evidence/order-malformed-bundle.json'));assert.equal(malformed.inputRows.length,2);assert.equal(malformed.inputRows[1].fieldError,true);assert.deepEqual(malformed.inputRows[1].extraFields,['unexpected-extra']);checks.push({case:'Extra-only invalid record remains unassigned/visible and survives run plus evidence export',source:'exact_independent_fixture_then_labelled_replay'});
 await importCSV(extraOnly);await page.locator('#order-error').waitFor({state:'visible'});assert.match(await page.locator('#order-error').textContent(),/1–20/);assert.match(await page.locator('#order-summary').textContent(),/Previous order file retained/);assert.match(await page.locator('#order-unassigned').textContent(),/unexpected-extra/);checks.push({case:'Exact21-nonempty-record fixture rejected before projection; prior two-record input retained',source:'exact_independent_fixture_local_input'});
 assert.ok([...resources].every(o=>['http://127.0.0.1:4331','https://rpc.mainnet.arc.io'].includes(o)));assert.ok(requests.every(({method,params})=>method==='eth_getTransactionReceipt'?params.length===1&&/^0x[0-9a-f]{64}$/.test(params[0]):method==='eth_getBlockByNumber'?params.length===2&&/^0x[0-9a-f]+$/.test(params[0])&&params[1]===false:['eth_chainId','eth_blockNumber'].includes(method)&&params.length===0));assert.deepEqual(errors,[]);checks.push({case:'Observed request origins and shapes exclude order IDs, totals, addresses, uploads, wallets and writes',source:'all_observed_network_requests'});passed=true;
}finally{await writeFile(new URL('evidence/order-validation.json',root),JSON.stringify({checkedAt:new Date().toISOString(),passed,checks,errors,requests,resources:[...resources],actualRPCReads:requests.filter(r=>r.source==='actual_public_rpc').length,maxPaymentRows:20,requestDelayMs:350,concurrency:1,writes:0,published:false,scope:'User-supplied order labels and associations; aggregate transaction net is not commercial settlement proof.',demo:'Made-up order IDs/totals over two unrelated third-party transactions; unknown all-zero hash explicitly labelled.'},null,2)+'\n');await browser.close();server.close();}
console.log(JSON.stringify({passed,checks:checks.length,actualRPCReads:requests.filter(r=>r.source==='actual_public_rpc').length,errors}));
