// Records actual automated UI interactions against public mainnet; never substitutes RPC fixtures.
import {chromium} from 'playwright';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const output=new URL('../release/demo/',import.meta.url);await mkdir(output,{recursive:true});process.env.PORT='4315';const {server}=await import('./server.mjs');
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1080},recordVideo:{dir:new URL('raw/',output).pathname,size:{width:1440,height:1080}},acceptDownloads:true});
const page=await context.newPage();const started=Date.now();const events=[],methods=[],errors=[];let live,zero,complete=false;
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(new URL(r.url()).origin==='https://rpc.mainnet.arc.io'&&r.method()==='POST'){const q=r.postDataJSON();methods.push(q.method);assert.ok(['eth_chainId','eth_getTransactionReceipt','eth_getBlockByNumber','eth_blockNumber'].includes(q.method));}});
const mark=text=>events.push({seconds:(Date.now()-started)/1000,text});const hold=ms=>page.waitForTimeout(ms);
const result=async status=>{await page.waitForFunction(()=>!document.getElementById('verify').disabled&&document.getElementById('loading').hidden,{}, {timeout:65000});assert.equal(await page.locator('#error').isVisible(),false,await page.locator('#error').textContent());assert.equal(await page.locator('#status').textContent(),status);};
const download=async(id,name)=>{const pending=page.waitForEvent('download');await page.locator(id).click();const d=await pending;await d.saveAs(new URL(name,output).pathname);return readFile(new URL(name,output),'utf8');};
try{
 mark('Arc Receipt v0.2 | automated local demo | real public mainnet reads | examples are not user earnings');await page.goto('http://127.0.0.1:4315');await hold(4500);
 await page.evaluate(()=>scrollTo({top:350,behavior:'smooth'}));await hold(1000);mark('Direct native transfer:100.01 incoming,0 outgoing,100.01 transaction net; customer intent unknown');await page.locator('#live-example').click();await result('Expected transaction net matched');assert.equal(await page.locator('#net').textContent(),'100.01');await hold(7000);
 mark('Native-only direct send: system log15,18 decimals,100010000000000000000 raw units; no ERC-20 mirror invented');await page.locator('#precision-detail summary').click();assert.deepEqual(await page.locator('.precision-grid code').allTextContents(),['100010000000000000000']);await page.locator('#precision-detail').scrollIntoViewIfNeeded();await hold(6500);
 mark('Export readable HTML plus JSON containing raw receipt and canonical block');const html=await download('#download-readable','public-receipt.html');assert.match(html,/100.01/);live=JSON.parse(await download('#download','public-receipt.json'));await hold(4500);
 mark('Import saved JSON: recompute claims, then fetch the transaction again');await page.locator('#receipt-file').setInputFiles(new URL('public-receipt.json',output).pathname);await page.locator('#recheck-note').waitFor({state:'visible',timeout:65000});await result('Expected transaction net matched');await page.locator('#recheck-note').scrollIntoViewIfNeeded();await hold(6500);
 mark('Expected transaction net differs by0.000001 USDC; exact comparison, no invoice-paid/unpaid decision');await page.locator('#amount').fill('100.010001');await page.locator('#verify').click();await result('Expected transaction net differs');assert.match(await page.locator('#amount-comparison').textContent(),/Below expected by 0.000001/);await page.locator('.receipt-summary').scrollIntoViewIfNeeded();await hold(6500);
 mark('Normal cirBTC-USDC swap intermediary:1458.033036 incoming and outgoing, net0; not merchant nonpayment evidence');await page.locator('#roundtrip-example').click();await result('Zero net flow observed');assert.equal(await page.locator('#net').textContent(),'0');await page.locator('.receipt-summary').scrollIntoViewIfNeeded();await hold(8000);
 await page.locator('#movement-detail summary').click();await page.locator('#movement-detail').scrollIntoViewIfNeeded();await hold(5000);zero=JSON.parse(await download('#download','public-zero-net.json'));assert.equal(zero.incomingUSDC,zero.outgoingUSDC);
 mark('Review boundaries: address control, intent, invoice allocation, partial payments, sweeps and mints need independent context');await page.locator('.scope-guide summary').click();await page.locator('.scope-guide').scrollIntoViewIfNeeded();await hold(6500);
 mark('Single-provider unsigned RPC observation, not cryptographic proof. No wallet, signing, transaction or gas. Local preview; public deployment pending.');await page.locator('.trust').scrollIntoViewIfNeeded();await hold(6000);assert.deepEqual(errors,[]);assert.equal(methods.length,16);assert.deepEqual([...new Set(methods)].sort(),['eth_blockNumber','eth_chainId','eth_getBlockByNumber','eth_getTransactionReceipt'].sort());complete=true;
}finally{
 const elapsed=(Date.now()-started)/1000;await context.close();const video=page.video();await video.saveAs(new URL('arc-receipt-real-demo.webm',output).pathname);await browser.close();server.close();
 const stamp=t=>{const ms=Math.floor(t*1000);return `${String(Math.floor(ms/3600000)).padStart(2,'0')}:${String(Math.floor(ms/60000)%60).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')},${String(ms%1000).padStart(3,'0')}`;};
 await writeFile(new URL('arc-receipt-real-demo.srt',output),events.map((e,i)=>`${i+1}\n${stamp(e.seconds)} --> ${stamp(events[i+1]?.seconds??elapsed)}\n${e.text}\n`).join('\n'));
 await writeFile(new URL('recording-evidence.json',output),JSON.stringify({recordedAt:new Date().toISOString(),complete,elapsedSeconds:elapsed,resolution:'1440x1080',capture:'Playwright uninterrupted browser video; headless fresh profile; no synthetic RPC responses; subtitles are separate annotations timed from page creation (small startup offset possible)',rpcMethods:methods,browserErrors:errors,positive:live?{tx:live.transactionHash,status:live.status,net:live.netReceivedUSDC}:null,negative:zero?{tx:zero.transactionHash,status:zero.status,incoming:zero.incomingUSDC,outgoing:zero.outgoingUSDC,net:zero.netReceivedUSDC}:null,chapters:events,noUserEarningsClaim:true,published:false},null,2)+'\n');
}
if(!complete)process.exitCode=1;else console.log('Real mainnet UI recording complete; saved locally, unpublished.');
