// Four reproducible technical workflows, not human usability or payment-intent evidence.
import {chromium} from 'playwright';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const root=new URL('../',import.meta.url),dir=new URL('evidence/workflows/',root);await mkdir(dir,{recursive:true});
process.env.PORT='4328';const {server}=await import('./server.mjs');
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true}),page=await context.newPage();
const methods=[],errors=[],cases=[];let passed=false;
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(new URL(r.url()).origin==='https://rpc.mainnet.arc.io'){const q=r.postDataJSON();methods.push({method:q.method,params:q.params});}});
const done=()=>page.waitForFunction(()=>!document.getElementById('verify').disabled&&document.getElementById('loading').hidden,{}, {timeout:65000});
const download=async(id,name)=>{const d=page.waitForEvent('download');await page.locator(id).click();const f=await d;await f.saveAs(new URL(name,dir).pathname);return readFile(new URL(name,dir),'utf8');};
const record=async(name,steps,start)=>{await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:new URL(name+'.png',dir).pathname,fullPage:true});const output=await page.evaluate(()=>Object.fromEntries(['status','incoming','outgoing','net','amount-comparison','case-context','expected-basis','hash-full','recipient-full','block-time','checked-time','recheck-note'].map(id=>[id,document.getElementById(id).textContent])));cases.push({name,source:'actual_public_rpc',steps,rpcReads:methods.length-start,output,screenshot:name+'.png'});};
try{
 await page.goto('http://127.0.0.1:4328');
 let start=methods.length;await page.locator('#start-review').click();await done();assert.equal(await page.locator('#status').textContent(),'Expected transaction net matched');assert.deepEqual(await Promise.all(['incoming','outgoing','net'].map(id=>page.locator('#'+id).textContent())),['100.01','0','100.01']);assert.match(await page.locator('#amount-comparison').textContent(),/Compared with transaction net/);assert.match(await page.locator('#expected-basis').textContent(),/Expected net 100.01 USDC/);const basis=await page.locator('.review-basis').boundingBox(),amount=await page.locator('.receipt-summary').boundingBox();assert.ok(basis.y+basis.height<=amount.y);await record('01-direct',['Open local UI','Choose Try the complete check in the first-review guide','Inspect incoming100.01 / outgoing0 / net100.01 and explicit expected-net comparison'],start);
 start=methods.length;await page.locator('#difference-example').click();await done();assert.equal(await page.locator('#status').textContent(),'Expected transaction net differs');assert.match(await page.locator('#amount-comparison').textContent(),/Below expected by 0.000001/);assert.match(await page.locator('#explanation').textContent(),/does not establish an unpaid invoice/);await record('02-exact-difference',['Choose preset Exact expected-net difference','Same actual transaction; expected net100.010001','Inspect exact0.000001 difference; no invoice-paid/unpaid decision'],start);
 start=methods.length;await page.locator('#roundtrip-example').click();await done();assert.deepEqual(await Promise.all(['incoming','outgoing','net'].map(id=>page.locator('#'+id).textContent())),['1458.033036','1458.033036','0']);assert.equal(await page.locator('#amount').inputValue(),'');assert.match(await page.locator('#case-context').textContent(),/normal cirBTC → USDC swap/);assert.match(await page.locator('#case-context').textContent(),/not merchant nonpayment evidence/);await page.locator('#precision-detail summary').click();assert.deepEqual(await page.locator('.precision-grid code').allTextContents(),['1458033036000000000000','1458033036','1458033036000000000000','1458033036']);await record('03-normal-swap',['Choose preset Normal swap intermediary','Inspect selected TakerPositionManager incoming/outgoing/net; expectation blank','Expand paired18/6 logs; treat normal routing as technical context'],start);
 start=methods.length;await page.locator('#live-example').click();await done();const saved=await download('#download','direct-evidence.json');const html=await download('#download-readable','direct-readable.html');assert.equal(JSON.parse(saved).reviewScope.comparisonBasis,'transaction_net');assert.match(html,/Single-provider unsigned RPC observation/);assert.match(html,/This single-transaction receipt does not aggregate partial payments across transactions/);assert.match(html,/separate order review sums user-assigned transaction-net observations; it does not prove commercial settlement/);assert.ok(!html.includes('<script'));
 const chooser=page.waitForEvent('filechooser');await page.locator('#import-result').click();await (await chooser).setFiles(new URL('direct-evidence.json',dir).pathname);await page.locator('#recheck-note').waitFor({state:'visible',timeout:65000});await done();assert.match(await page.locator('#recheck-note').textContent(),/Recheck consistent/);assert.equal(await page.locator('#net').textContent(),'100.01');await page.locator('.scope-guide summary').click();assert.match(await page.locator('.scope-guide').textContent(),/Address control and intent/);assert.match(await page.locator('.scope-guide').textContent(),/Partial payments/);assert.match(await page.locator('.scope-guide').textContent(),/Sweeps and collection/);await record('04-evidence-handoff',['Return to preset Direct native transfer (preparation fresh read)','Download readable HTML and JSON with raw receipt/block and review scope','Choose Recheck saved JSON beside result exports and import that export','Recompute saved claims then fresh fixed-RPC query; inspect consistent recheck and review boundaries'],start);
 assert.equal(methods.length,20);assert.deepEqual([...new Set(methods.map(x=>x.method))].sort(),['eth_blockNumber','eth_chainId','eth_getBlockByNumber','eth_getTransactionReceipt'].sort());assert.deepEqual(errors,[]);passed=true;
}finally{await writeFile(new URL('acceptance.json',dir),JSON.stringify({checkedAt:new Date().toISOString(),passed,workflowCount:cases.length,cases,rpcRequests:methods,browserErrors:errors,source:'Independent automated local workflows with real public RPC reads. No RPC fixtures, user study, task timing benefit, customer intent or ownership validation.',samplesAreNotUserEarnings:true,published:false},null,2)+'\n');await browser.close();server.close();}
console.log(JSON.stringify({passed,workflows:cases.length,actualRPCReads:methods.length,errors}));
